[build]
  builder = "nixpacks"
  workdir = "Softellio-Backend"

[deploy]
  startCommand = "cd Softellio-Backend && npm run start:prod"
  healthcheckPath = "/health"
  healthcheckTimeout = 100
  restartPolicyType = "always"